// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Agent.proto

#ifndef PROTOBUF_INCLUDED_Agent_2eproto
#define PROTOBUF_INCLUDED_Agent_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_Agent_2eproto 

namespace protobuf_Agent_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_Agent_2eproto
namespace com {
namespace xum {
namespace proto {
namespace agent {
class AgentRegister;
class AgentRegisterDefaultTypeInternal;
extern AgentRegisterDefaultTypeInternal _AgentRegister_default_instance_;
}  // namespace agent
}  // namespace proto
}  // namespace xum
}  // namespace com
namespace google {
namespace protobuf {
template<> ::com::xum::proto::agent::AgentRegister* Arena::CreateMaybeMessage<::com::xum::proto::agent::AgentRegister>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace com {
namespace xum {
namespace proto {
namespace agent {

// ===================================================================

class AgentRegister : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.xum.proto.agent.AgentRegister) */ {
 public:
  AgentRegister();
  virtual ~AgentRegister();

  AgentRegister(const AgentRegister& from);

  inline AgentRegister& operator=(const AgentRegister& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AgentRegister(AgentRegister&& from) noexcept
    : AgentRegister() {
    *this = ::std::move(from);
  }

  inline AgentRegister& operator=(AgentRegister&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AgentRegister& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AgentRegister* internal_default_instance() {
    return reinterpret_cast<const AgentRegister*>(
               &_AgentRegister_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AgentRegister* other);
  friend void swap(AgentRegister& a, AgentRegister& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AgentRegister* New() const final {
    return CreateMaybeMessage<AgentRegister>(NULL);
  }

  AgentRegister* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AgentRegister>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AgentRegister& from);
  void MergeFrom(const AgentRegister& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgentRegister* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string agent_name = 1;
  void clear_agent_name();
  static const int kAgentNameFieldNumber = 1;
  const ::std::string& agent_name() const;
  void set_agent_name(const ::std::string& value);
  #if LANG_CXX11
  void set_agent_name(::std::string&& value);
  #endif
  void set_agent_name(const char* value);
  void set_agent_name(const char* value, size_t size);
  ::std::string* mutable_agent_name();
  ::std::string* release_agent_name();
  void set_allocated_agent_name(::std::string* agent_name);

  // string host_ip = 2;
  void clear_host_ip();
  static const int kHostIpFieldNumber = 2;
  const ::std::string& host_ip() const;
  void set_host_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_host_ip(::std::string&& value);
  #endif
  void set_host_ip(const char* value);
  void set_host_ip(const char* value, size_t size);
  ::std::string* mutable_host_ip();
  ::std::string* release_host_ip();
  void set_allocated_host_ip(::std::string* host_ip);

  // @@protoc_insertion_point(class_scope:com.xum.proto.agent.AgentRegister)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr agent_name_;
  ::google::protobuf::internal::ArenaStringPtr host_ip_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_Agent_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AgentRegister

// string agent_name = 1;
inline void AgentRegister::clear_agent_name() {
  agent_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AgentRegister::agent_name() const {
  // @@protoc_insertion_point(field_get:com.xum.proto.agent.AgentRegister.agent_name)
  return agent_name_.GetNoArena();
}
inline void AgentRegister::set_agent_name(const ::std::string& value) {
  
  agent_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.xum.proto.agent.AgentRegister.agent_name)
}
#if LANG_CXX11
inline void AgentRegister::set_agent_name(::std::string&& value) {
  
  agent_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.xum.proto.agent.AgentRegister.agent_name)
}
#endif
inline void AgentRegister::set_agent_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  agent_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.xum.proto.agent.AgentRegister.agent_name)
}
inline void AgentRegister::set_agent_name(const char* value, size_t size) {
  
  agent_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.xum.proto.agent.AgentRegister.agent_name)
}
inline ::std::string* AgentRegister::mutable_agent_name() {
  
  // @@protoc_insertion_point(field_mutable:com.xum.proto.agent.AgentRegister.agent_name)
  return agent_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AgentRegister::release_agent_name() {
  // @@protoc_insertion_point(field_release:com.xum.proto.agent.AgentRegister.agent_name)
  
  return agent_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AgentRegister::set_allocated_agent_name(::std::string* agent_name) {
  if (agent_name != NULL) {
    
  } else {
    
  }
  agent_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), agent_name);
  // @@protoc_insertion_point(field_set_allocated:com.xum.proto.agent.AgentRegister.agent_name)
}

// string host_ip = 2;
inline void AgentRegister::clear_host_ip() {
  host_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AgentRegister::host_ip() const {
  // @@protoc_insertion_point(field_get:com.xum.proto.agent.AgentRegister.host_ip)
  return host_ip_.GetNoArena();
}
inline void AgentRegister::set_host_ip(const ::std::string& value) {
  
  host_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.xum.proto.agent.AgentRegister.host_ip)
}
#if LANG_CXX11
inline void AgentRegister::set_host_ip(::std::string&& value) {
  
  host_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.xum.proto.agent.AgentRegister.host_ip)
}
#endif
inline void AgentRegister::set_host_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  host_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.xum.proto.agent.AgentRegister.host_ip)
}
inline void AgentRegister::set_host_ip(const char* value, size_t size) {
  
  host_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.xum.proto.agent.AgentRegister.host_ip)
}
inline ::std::string* AgentRegister::mutable_host_ip() {
  
  // @@protoc_insertion_point(field_mutable:com.xum.proto.agent.AgentRegister.host_ip)
  return host_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AgentRegister::release_host_ip() {
  // @@protoc_insertion_point(field_release:com.xum.proto.agent.AgentRegister.host_ip)
  
  return host_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AgentRegister::set_allocated_host_ip(::std::string* host_ip) {
  if (host_ip != NULL) {
    
  } else {
    
  }
  host_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), host_ip);
  // @@protoc_insertion_point(field_set_allocated:com.xum.proto.agent.AgentRegister.host_ip)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace agent
}  // namespace proto
}  // namespace xum
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_Agent_2eproto
